name: GLSLsmith tests in isolation

on: [push]

jobs:
  build-dependencies:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules:'recursive'
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      - name: Set up GlslangValidator
        run: sudo apt-get install -y glslang-tools
      
      - name: Set up GraphicsFuzz
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      
      - name: Build GraphicsFuzz
        run: cd graphicsfuzz && mvn install
      
      - name: Tests with pytest
        run: |
         cd scripts && python -m pytest --ignore graphicsfuzz
