name: GLSLsmith tests

on: [push]

jobs:
  Check-glslsmith-scripts:

    runs-on: ubuntu-latest
    
    steps:
      # Setting up the repository
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      # Unzip dependencies (Swiftshader / Shadertrap)
      - name: Install Unzip
        run: |
          sudo apt-get install unzip
      
      # Python code execution
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Java dependencies
      - name: Set up GlslangValidator
        run: sudo apt-get install -y glslang-tools
      
      - name: Set up GraphicsFuzz with cache
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      
      - name: Build GraphicsFuzz
        run: cd graphicsfuzz && mvn -Dmaven.test.skip=true install
      

      # llvmpipe
      - name: Install mesa dependencies
        run: $GITHUB_WORKSPACE/.github/workflows/llvmpipe_dep.sh

      - name: Verify if llvmpipe is in cache
        id: llvmpipe-cache
        uses: actions/cache@v2
        with:
          path: |
           ~/llvmpipe
          key: llvmpipe-

      - name: Install llvmpipe
        if: steps.llvmpipe-cache.outputs.cache-hit != 'true'
        run:
          mkdir ~/llvmpipe && cd ~/llvmpipe && $GITHUB_WORKSPACE/.github/workflows/setup_llvmpipe.sh

      # Swiftshader
      - name: Install Swiftshader
        run: |
          mkdir ~/angle && cd ~/angle && curl -fsSL -o angle.zip https://github.com/google/gfbuild-angle/releases/download/github%2Fgoogle%2Fgfbuild-angle%2F96ab6566490495f472cd239997701b201c7a48ac/gfbuild-angle-96ab6566490495f472cd239997701b201c7a48ac-Linux_x64_Debug.zip && unzip angle.zip

      - name: Copy Shadertrap dependencies
        run:
          cp ./lib/libEGL.so ./lib/libEGL.so.1
          
      # Shadertrap
      - name: Install Shadertrap
        run: |
          mkdir ~/swiftshader && cd ~/swiftshader && curl -fsSL -o shadertrap.zip https://github.com/google/gfbuild-shadertrap/releases/download/github%2Fgoogle%2Fgfbuild-shadertrap%2Fb4e8470b3d69ef063b318248ae47e25e3081199c/gfbuild-shadertrap-b4e8470b3d69ef063b318248ae47e25e3081199c-Linux_x64_Release.zip && unzip shadertrap.zip

      # Tests 
      - name: Tests with pytest
        run: |
         cd scripts && python -m pytest --ignore graphicsfuzz
