name: GLSLsmith tests in isolation

on: [push]

jobs:
  Check-glslsmith-scripts:

    runs-on: ubuntu-latest
    
    steps:
      # Setting up the repository
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      
      # Python code execution
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # Java dependencies
      - name: Set up GlslangValidator
        run: sudo apt-get install -y glslang-tools
      
      - name: Set up GraphicsFuzz with cache
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      
      - name: Build GraphicsFuzz
        run: cd graphicsfuzz && mvn -Dmaven.test.skip=true install
      

      # llvmpipe
      - name: Install llvmpipe
        run:
          mkdir ~/llvmpipe && cd ~/llvmpipe && $GITHUB_WORKSPACE/.github/workflows/setup_llvmpipe.sh

      # Shadertrap
      - name: Install Shadertrap
        run: |
          curl -fsSL -o shadertrap.zip https://github.com/google/gfbuild-shadertrap/releases/download/github%2Fgoogle%2Fgfbuild-shadertrap%2Fb4e8470b3d69ef063b318248ae47e25e3081199c/gfbuild-shadertrap-b4e8470b3d69ef063b318248ae47e25e3081199c-Linux_x64_Release.zip && sudo apt-get install -y unzip && unzip shadertrap.zip

      # Tests 
      - name: Tests with pytest
        run: |
         cd scripts && python -m pytest --ignore graphicsfuzz
